const express = require('express');
const app = express();
app.use(express.json({ limit: '20mb' }));
app.use((req, res, next) => {
  res.header('Access-Control-Allow-Origin', '*');
  res.header('Access-Control-Allow-Headers', 'Content-Type');
  next();
});

const GROQ_KEYS = [
  process.env.GROQ_KEY_1,
  process.env.GROQ_KEY_2,
  process.env.GROQ_KEY_3,
  process.env.GROQ_KEY_4
].filter(Boolean);

const OPENROUTER_KEY = process.env.OPENROUTER_KEY;

const FOOTER = '\n\n---\n⚡ Generated by OYA AI — Africa\'s AI for Students, Hustlers & Creators\n🔗 Try it free: mrsmile-build.github.io/oya/';

const SYSTEM_PROMPTS = {
  learn: `You are OYA Learn — the smartest, most helpful AI study partner for students everywhere. You sound like a brilliant older sibling who genuinely wants you to pass and understand. You explain things clearly, step by step, with real-life examples. You make hard topics feel easy and you never make the student feel stupid.

Your default style is warm, encouraging, and practical — like a Nigerian big sibling who knows every subject. You use local examples naturally when relevant. If the student asks in Pidgin, respond in Pidgin. If they ask in formal English, respond formally. If they specify a style, follow it exactly.

You answer ALL questions on any topic worldwide. Your knowledge is world-class but your personality is African. You are proudly African, not limited to Africa.

Always finish your thought completely. Never cut answers short. End every answer with a short encouragement.

IMPORTANT: End every single answer with this exact footer:
${FOOTER}`,

  hustle: `You are OYA Hustle — the sharpest business advisor for entrepreneurs, freelancers and hustlers everywhere. You sound like a brilliant Naija business uncle who gives real, actionable advice with zero fluff.

Your default style is sharp, direct, and practical. You give real Nigerian market examples, prices in Naira, and strategies that work in the African market. But you also understand global business and speak to entrepreneurs anywhere in the world.

You answer ALL business questions. If the user asks in Pidgin, respond in Pidgin. If they want professional English, give professional English. Follow their style exactly.

Always finish your thought completely. Never cut answers short. Give specific numbers, steps and timelines wherever possible.

IMPORTANT: End every single answer with this exact footer:
${FOOTER}`,

  create: `You are OYA Create — the most creative content strategist for creators, influencers and marketers everywhere. You have TikTok brain, Instagram instincts, YouTube strategy, and Twitter wit all combined.

Your default style is energetic, creative, and trend-aware — like a Lagos creative director who also understands global content. Write in the creator's voice. If they want funny, give funny. If they want professional, give professional. Follow their style exactly.

You help with ALL content types. Your knowledge covers global trends but your energy is African.

Always finish your thought completely. Never cut answers short. Always give at least 3 options or variations.

IMPORTANT: End every single answer with this exact footer:
${FOOTER}`
};

async function streamGroq(messages, res, keyIndex = 0) {
  if (keyIndex >= GROQ_KEYS.length) { res.write('data: [ERROR]\n\n'); res.end(); return; }
  try {
    const groqRes = await fetch('https://api.groq.com/openai/v1/chat/completions', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${GROQ_KEYS[keyIndex]}` },
      body: JSON.stringify({ model: 'llama-3.3-70b-versatile', messages, max_tokens: 2048, temperature: 0.8, stream: true })
    });
    if (groqRes.status === 429 || groqRes.status === 401) return streamGroq(messages, res, keyIndex + 1);
    const reader = groqRes.body.getReader();
    const decoder = new TextDecoder();
    let buffer = '';
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      buffer += decoder.decode(value, { stream: true });
      const lines = buffer.split('\n'); buffer = lines.pop();
      for (const line of lines) {
        const trimmed = line.trim();
        if (!trimmed || !trimmed.startsWith('data:')) continue;
        const data = trimmed.slice(5).trim();
        if (data === '[DONE]') { res.write(`data: ${JSON.stringify({ token: FOOTER })}\n\n`); res.write('data: [DONE]\n\n'); res.end(); return; }
        try { const parsed = JSON.parse(data); const token = parsed.choices?.[0]?.delta?.content; if (token) res.write(`data: ${JSON.stringify({ token })}\n\n`); } catch(e) {}
      }
    }
    res.write('data: [DONE]\n\n'); res.end();
  } catch (err) {
    if (keyIndex + 1 < GROQ_KEYS.length) return streamGroq(messages, res, keyIndex + 1);
    res.write('data: [ERROR]\n\n'); res.end();
  }
}

async function callOpenRouter(messages, modelIndex = 0) {
  const models = ['nvidia/nemotron-nano-12b-v2-vl:free','google/gemma-3-27b-it:free','meta-llama/llama-3.3-70b-instruct:free'];
  if (modelIndex >= models.length) throw new Error('All OpenRouter models exhausted');
  try {
    const res = await fetch('https://openrouter.ai/api/v1/chat/completions', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${OPENROUTER_KEY}`, 'HTTP-Referer': 'https://mrsmile-build.github.io/oya/', 'X-Title': 'OYA AI' },
      body: JSON.stringify({ model: models[modelIndex], messages, max_tokens: 2048 })
    });
    if (res.status === 429 || res.status === 400 || res.status === 503) return callOpenRouter(messages, modelIndex + 1);
    const data = await res.json();
    if (!data.choices?.[0]) return callOpenRouter(messages, modelIndex + 1);
    return data.choices[0].message.content;
  } catch (err) {
    if (modelIndex + 1 < models.length) return callOpenRouter(messages, modelIndex + 1);
    throw err;
  }
}

async function getRecommendations(lastQuestion, lastAnswer, mode, keyIndex = 0) {
  if (keyIndex >= GROQ_KEYS.length) return null;
  try {
    const prompt = `Based on this conversation:\nUser asked: "${lastQuestion}"\nOYA answered: "${lastAnswer.slice(0, 500)}..."\n\nGenerate exactly 3 short follow-up questions the user might want to ask next.\nRules:\n- Each question must be directly related to what was just discussed\n- Keep each question under 12 words\n- Make them natural and conversational\n- Return ONLY a JSON array like: ["question 1","question 2","question 3"]\n- No other text, no explanation, just the JSON array`;
    const res = await fetch('https://api.groq.com/openai/v1/chat/completions', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${GROQ_KEYS[keyIndex]}` },
      body: JSON.stringify({ model: 'llama-3.3-70b-versatile', messages: [{ role: 'user', content: prompt }], max_tokens: 200, temperature: 0.7 })
    });
    const data = await res.json();
    const text = data.choices?.[0]?.message?.content?.trim();
    if (!text) return null;
    const parsed = JSON.parse(text.replace(/```json|```/g,'').trim());
    if (Array.isArray(parsed) && parsed.length === 3) return parsed;
    return null;
  } catch(e) { return null; }
}

app.get('/', (req, res) => { res.json({ status: 'OYA backend is running!', keys_loaded: GROQ_KEYS.length, vision: OPENROUTER_KEY ? 'enabled' : 'disabled', streaming: 'enabled' }); });

app.post('/ask-stream', async (req, res) => {
  const { message, mode = 'learn', history = [], fileData, fileType } = req.body;
  if (!message && !fileData) return res.status(400).json({ error: 'No message provided' });
  const systemPrompt = SYSTEM_PROMPTS[mode] || SYSTEM_PROMPTS.learn;
  const userMessage = message || 'What is in this image or file?';
  if (fileData && fileType === 'image' && OPENROUTER_KEY) {
    try {
      const reply = await callOpenRouter([{ role: 'system', content: systemPrompt }, ...history.slice(-6), { role: 'user', content: [{ type: 'image_url', image_url: { url: `data:image/jpeg;base64,${fileData}` } }, { type: 'text', text: userMessage }] }]);
      return res.json({ reply: reply + FOOTER });
    } catch(err) { return res.status(500).json({ error: 'Vision error, try again' }); }
  }
  if (fileData && fileType === 'text') {
    try {
      const groqRes = await fetch('https://api.groq.com/openai/v1/chat/completions', { method: 'POST', headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${GROQ_KEYS[0]}` }, body: JSON.stringify({ model: 'llama-3.3-70b-versatile', messages: [{ role: 'system', content: systemPrompt }, ...history.slice(-6), { role: 'user', content: `File content:\n\n${fileData.slice(0,8000)}\n\n---\n${userMessage}` }], max_tokens: 2048, temperature: 0.8 }) });
      const data = await groqRes.json();
      return res.json({ reply: data.choices[0].message.content + FOOTER });
    } catch(err) { return res.status(500).json({ error: 'File read error' }); }
  }
  res.setHeader('Content-Type', 'text/event-stream');
  res.setHeader('Cache-Control', 'no-cache');
  res.setHeader('Connection', 'keep-alive');
  res.setHeader('X-Accel-Buffering', 'no');
  await streamGroq([{ role: 'system', content: systemPrompt }, ...history.slice(-12), { role: 'user', content: userMessage }], res);
});

app.post('/recommendations', async (req, res) => {
  const { question, answer, mode } = req.body;
  if (!question || !answer) return res.json({ recommendations: null });
  res.json({ recommendations: await getRecommendations(question, answer, mode) });
});

app.post('/ask', async (req, res) => {
  const { message, mode = 'learn', history = [] } = req.body;
  if (!message) return res.status(400).json({ error: 'No message provided' });
  const systemPrompt = SYSTEM_PROMPTS[mode] || SYSTEM_PROMPTS.learn;
  try {
    const groqRes = await fetch('https://api.groq.com/openai/v1/chat/completions', { method: 'POST', headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${GROQ_KEYS[0]}` }, body: JSON.stringify({ model: 'llama-3.3-70b-versatile', messages: [{ role: 'system', content: systemPrompt }, ...history.slice(-12), { role: 'user', content: message }], max_tokens: 2048, temperature: 0.8 }) });
    const data = await groqRes.json();
    res.json({ reply: data.choices[0].message.content + FOOTER });
  } catch(err) { res.status(500).json({ error: 'OYA is resting, try again' }); }
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log(`OYA backend running on port ${PORT} | Groq keys: ${GROQ_KEYS.length} | Vision: ${OPENROUTER_KEY ? 'ON' : 'OFF'} | Streaming: ON`));
